---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
        commitId: "{{ .Values.image.commitId }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        ports:
        - containerPort: {{ .Values.image.port }}
      env:
        - name: MYSQL_USER
          value: {{ .Values.envVariables.mysqlusername }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlpass
              key: "{{ .Values.envVariables.mysqlpassword }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.envVariables.mysqldb }}"
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.envVariables.mysqlrootpasswd }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim